export {
    profileReducer,
    setMovie,
    deleteMovie,
    setProfileMovies,
    getIsDrawerMovieTagsOpen,
    setSelectMovie,
    setTagToMovie,
    updateMovie,
    deleteTagFromMovie,
    deleteTagFromMovies,
    updateTags,
    addEnableFilters,
    removeEnableFilters,
    getGenres,
    setSelectGenres,
} from './profileSlice'
