export {
    profileReducer,
    setMovie,
    deleteMovie,
    setProfileMovies,
    getIsDrawerMovieTagsOpen,
    updateMovie,
    deleteTagFromMovies,
    updateTags,
    addSelectTags,
    addSelectIgnoreTags,
    removeSelectTags,
    removeSelectIgnoreTags,
    setSortMovies,
    getGenres,
    setGenreFlagStatus,
    addSelectGenres,
    addSelectIgnoreGenres,
    removeSelectGenres,
    removeSelectIgnoreGenres,
    setSearchMovie,
    setMovieIsWithoutDateInBack,
} from './profileSlice'
