import {
    requestMovies,
    requestSaveMovie,
    requestDeleteMovie,
    requestProfileMovies,
    requestMovieTags,
    requestMovieTree,
    requestUpdateProfileMovies,
    requestSaveTag,
    requestDeleteTag,
    requestUpdateTags,
    requestUpdateMovieTags,
    requestDeleteMovieTags,
    requestGenres,
} from './requests.ts'

export const API = {
    requestMovies,
    requestSaveMovie,
    requestDeleteMovie,
    requestProfileMovies,
    requestMovieTags,
    requestMovieTree,
    requestUpdateProfileMovies,
    requestSaveTag,
    requestDeleteTag,
    requestUpdateTags,
    requestUpdateMovieTags,
    requestDeleteMovieTags,
    requestGenres,
}
