export {
    layoutReducer,
    setLanguage,
    sestIsModalDetailsOpen,
    setIsAddMovieModalOpen,
    setIsAddPersonModalOpen,
    setArtistId,
    setModelContent,
    deleteModelContent,
    deleteAllModelContent,
    setSelectMovie,
    setSelectPerson,
    setTagToSelectMovie,
    deleteTagFromMovie,
    updateMovieDateViewing,
    addMovieDateViewing,
    deleteMovieDateViewing,
} from './layoutSlice'
